-- MySQL Script generated by MySQL Workbench
-- Fri May 19 21:49:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbactividad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbactividad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbactividad` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbactividad` ;

-- -----------------------------------------------------
-- Table `dbactividad`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbactividad`.`usuarios` (
  `cc` INT NOT NULL,
  `pass` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `apellido` VARCHAR(50) NULL DEFAULT NULL,
  `genero` VARCHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`cc`),
  UNIQUE INDEX `unique_email` (`email` ASC) VISIBLE,
  INDEX `idx_cc` (`cc` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbactividad`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbactividad`.`contratos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaFirma` DATE NULL DEFAULT NULL,
  `fechaInicio` DATE NULL DEFAULT NULL,
  `fechaFin` DATE NULL DEFAULT NULL,
  `empresa` VARCHAR(50) NULL DEFAULT NULL,
  `empleado` VARCHAR(50) NULL DEFAULT NULL,
  `funciones` VARCHAR(255) NULL DEFAULT NULL,
  `monto` DECIMAL(10,2) NULL DEFAULT NULL,
  `frecuenciaDePago` VARCHAR(50) NULL DEFAULT NULL,
  `usuariocc` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuariocc` (`usuariocc` ASC) VISIBLE,
  CONSTRAINT `contratos_ibfk_1`
    FOREIGN KEY (`usuariocc`)
    REFERENCES `dbactividad`.`usuarios` (`cc`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
